outfile: main.o add_begin.o add_middle.o add_end.o rev_links.o count.o delete_node.o print.o
	cc main.o add_begin.o add_middle.o add_end.o rev_links.o count.o print.o delete_node.o -o outfile
main.o:main.c
	cc -c main.c
add_begin.o:add_begin.c
	cc -c add_begin.c
add_middle.o:add_middle.c
	cc -c add_middle.c
add_end.o:add_end.c
	cc -c add_end.c
rev_links.o:rev_links.c
	cc -c rev_links.c
count.o:count.c
	cc -c count.c
delete_node.o:delete_node.c
	cc -c delete_node.c
print.o:print.c
	cc -c print.c
