outfile: main.o _save_record.o add_begin.o add_end.o add_middle.o print.o count_record.o print_rev.o rev_data.o rev_data_link.o rev_link_recursion.o ret_data_file.o delete_r.o
	cc main.o _save_record.o add_begin.o add_end.o add_middle.o print.o count_record.o print_rev.o rev_data.o rev_data_link.o rev_link_recursion.o delete_r.o ret_data_file.o -o outfile
main.o:main.c
	cc -c main.c
_save_record.o:_save_record.c
	cc -c _save_record.c
add_bigin.o:add_begin.c
	cc -c add_begin.c
add_end.o:add_end.c
	cc -c add_end.c
add_middle.o:add_middle.c
	cc -c add_middle.c
print.o:print.c
	cc -c print.c
count_record.o:count_record.c
	cc -c count_record.c
print_rev.o:print_rev.c
	cc -c print_rev.c
rev_data.o:rev_data.c
	cc -c rev_data.c
rev_data_link.o:rev_data_link.c
	cc -c rev_data_link.c
rev_link_recursion.o:rev_link_recursion.c
	cc -c rev_link_recursion.c
delete_r.o:delete_r.c
	cc -c delete_r.c
ret_data_file.o:ret_data_file.c
	cc -c ret_data_file.c
