out:add_node.o pre_order.o post_order.o in_order.o search.o delete_node.o main.o
	cc add_node.o pre_order.o post_order.o in_order.o search.o delete_node.o main.o -o out
add_node.o:add_node.c
	cc -c add_node.c
pre_order.o:pre_order.c
	cc -c pre_order.c
post_order.o:post_order.c
	cc -c post_order.c
in_order.o:in_order.c
	cc -c in_order.c
search.o:search.c
	cc -c search.c
delete_node.o:delete_node.c
	cc -c delete_node.c
main.o:main.c
	cc -c main.c
